language: ruby
os: linux
sudo: required
services:
- docker
rvm:
- 2.6.4
before_install:
- gem install awesome_bot
script:
- awesome_bot --skip-save-results slides/timeline/*.md -w tachingchen.com
- awesome_bot --skip-save-results slides/topic/*.md -w tachingchen.com
- awesome_bot --skip-save-results slides/coscup/*.md